import { THREE_D_MAP_RENDERER } from "../threeDMapConstants";

export const FIRST_PERSON_CAMERA = {
	FOV: 72,
	NEAR: 0.04,
	FAR: THREE_D_MAP_RENDERER.CAMERA_FAR,
	POSITION_SMOOTHING: 10,
	ACTIVE_POSITION_SMOOTHING: 15,
	HEIGHT_BY_SIZE: {
		"extra-small": 0.7,
		small: 0.95,
		medium: 1.15,
		large: 1.4,
	},
	PITCH_LIMIT: Math.PI / 2 - 0.08,
} as const;

export const FIRST_PERSON_CONTROLS = {
	MOUSE_SENSITIVITY: 0.0022,
	MOVE_UNITS_PER_SECOND: 4.2,
	FLY_UNITS_PER_SECOND: 3.2,
	SYNC_IDLE_DEBOUNCE_MS: 450,
} as const;

export const FIRST_PERSON_PHYSICS = {
	GRAVITY: 22,
	JUMP_HEIGHT: 1.15,
	GROUND_ACCELERATION: 42,
	AIR_ACCELERATION: 11,
	FLY_ACCELERATION: 28,
	GROUND_FRICTION: 34,
	AIR_DRAG: 1.2,
	FLY_DAMPING: 12,
	STEP_HEIGHT: 0.68,
	STEP_HEIGHT_MARGIN: 0.12,
	STEP_UP_MIN_HEIGHT: 0.03,
	STEP_PROGRESS_TOLERANCE: 0.02,
	STEP_DOWN_SNAP_DISTANCE: 0.68,
	GROUND_SNAP_DISTANCE: 0.16,
	MAX_SUBSTEP_DISTANCE: 0.055,
	MAX_SUBSTEPS: 24,
	CAPSULE_HEAD_CLEARANCE: 0.24,
	COLLISION_EPSILON: 0.000001,
	SETTLED_SPEED: 0.045,
	MIN_WORLD_Y: -20,
	RADIUS_BY_SIZE: {
		"extra-small": 0.16,
		small: 0.22,
		medium: 0.3,
		large: 0.38,
	},
} as const;

export const FIRST_PERSON_KEY_CODES = [
	"KeyW",
	"KeyA",
	"KeyS",
	"KeyD",
	"Space",
	"ShiftLeft",
	"ShiftRight",
] as const;

export const MOVEMENT_STATE_UPDATE_MS = 120;
