export const THREE_D_MAP_RENDERER = {
	MAX_PIXEL_RATIO: 1.5,
	CAMERA_NEAR: 0.1,
	CAMERA_FAR: 2000,
} as const;

export const THREE_D_MAP_CAMERA = {
	FRAMING_MULTIPLIER: 0.85,
	DISTANCE_MULTIPLIER: 2.5,
} as const;

export const THREE_D_MAP_LIGHTING = {
	HEMISPHERE_SKY_COLOR: 0xffffff,
	HEMISPHERE_GROUND_COLOR: 0x8899aa,
	HEMISPHERE_INTENSITY_MULTIPLIER: 0.6,
	DIRECTIONAL_COLOR: 0xffffff,
	DIRECTIONAL_INTENSITY_MULTIPLIER: 1.15,
	DIRECTIONAL_POSITION_X_SCALE: -0.65,
	DIRECTIONAL_POSITION_Y_SCALE: 1.25,
	DIRECTIONAL_POSITION_Z_SCALE: 0.8,
} as const;

export const THREE_D_MAP_SHADOW = {
	MIN_CAMERA_HALF_SIZE: 4,
	CAMERA_HALF_SIZE_PADDING: 2,
	MIN_CAMERA_DEPTH: 40,
	CAMERA_DEPTH_EXTENT_MULTIPLIER: 3,
	CAMERA_DEPTH_ELEVATION_MULTIPLIER: 3,
	CAMERA_DEPTH_PADDING: 10,
	CAMERA_NEAR: 0.5,
	MAP_SIZE: 4096,
	BIAS: 0.000,
	NORMAL_BIAS: 0.01,
} as const;

export const THREE_D_MAP_CONTROLS = {
	DAMPING_FACTOR: 0.05,
	MIN_ZOOM: 0.2,
	MAX_ZOOM: 8,
	MIN_PAN_LIMIT_RADIUS: 4,
	PAN_LIMIT_ELEVATION_SCALE: 0.5,
	PAN_LIMIT_PADDING: 2,
} as const;

export const THREE_D_TERRAIN_MATERIAL = {
	ROUGHNESS: 0.85,
	METALNESS: 0,
} as const;

export const THREE_D_MAP_BLOOM = {
	INTENSITY: 0.72,
	LUMINANCE_THRESHOLD: 1.05,
	LUMINANCE_SMOOTHING: 0.12,
	RADIUS: 0.45,
	LEVELS: 5,
	MULTISAMPLING: 4,
} as const;

export const THREE_D_MOVEMENT_HIGHLIGHT = {
	FULL_RANGE_COLOR: 0xfa4398,
	REMAINING_RANGE_COLOR: 0x06b6d4,
	HOVER_COLOR: 0x2563eb,
	FULL_RANGE_OPACITY: 0.38,
	REMAINING_RANGE_OPACITY: 0.44,
	HOVER_OPACITY: 0.42,
	TILE_SIZE: 0.92,
	Y_OFFSET: 0.018,
	RENDER_ORDER: 80,
	HOVER_RENDER_ORDER: 82,
} as const;

export const THREE_D_STICKER_TEXTURE = {
	SIZE: 256,
	FONT_SIZE: 142,
	BACKDROP_RADIUS: 88,
	BACKDROP_INNER_COLOR: "rgba(15, 23, 42, 0.36)",
	BACKDROP_OUTER_COLOR: "rgba(15, 23, 42, 0)",
	SHADOW_COLOR: "rgba(0, 0, 0, 0.78)",
	SHADOW_BLUR: 16,
	SHADOW_OFFSET_Y: 5,
	FONT_FAMILY: "\"Segoe UI Emoji\", \"Apple Color Emoji\", \"Noto Color Emoji\", sans-serif",
} as const;

export const THREE_D_STICKER_PLACEMENT = {
	BASE_Y_GAP: 0.24,
	WORLD_SIZE_MULTIPLIER: 0.72,
	MIN_WORLD_SIZE: 0.52,
	MAX_WORLD_SIZE: 1.05,
	RENDER_ORDER: 160,
	BOB_HEIGHT: 0.045,
	BOB_SPEED: 4.2,
	POP_DURATION_MS: 180,
	POP_START_SCALE: 0.72,
} as const;

export const THREE_D_PING_MARKER = {
	COLOR: 0x22d3ee,
	ARROW_FILL: "#67e8f9",
	ARROW_STROKE: "#0e7490",
	TILE_Y_OFFSET: 0.018,
	ARROW_BASE_Y_OFFSET: 0.60,
	ARROW_BOUNCE_HEIGHT: 0.16,
	ARROW_BOUNCE_PERIOD_MS: 600,
	PULSE_PERIOD_MS: 700,
	PULSE_SCALE_MULTIPLIER: 0.25,
	FADE_HOLD_PROGRESS: 0.6,
	FILL_OPACITY: 0.18,
	OUTLINE_OPACITY: 0.85,
	OUTLINE_WIDTH: 0.08,
	RENDER_ORDER: 170,
	ARROW_TEXTURE_SIZE: 192,
	ARROW_FONT_SIZE: 136,
	ARROW_FONT_WEIGHT: 800,
	ARROW_FONT_FAMILY: "Inter, system-ui, sans-serif",
	ARROW_LINE_WIDTH: 12,
	ARROW_TEXT: "🡇",
	ARROW_TEXT_Y_OFFSET: 4,
	ARROW_WORLD_SIZE: 0.72,
} as const;

export const THREE_D_PING_INPUT = {
	CLICK_DRAG_THRESHOLD_PX: 5,
} as const;
