/*
 * This file is generated by scripts/generate-default-voxel-stamps.mjs.
 * Run npm run generate:stamps after changing .vox files under public/stamps.
 */

import {
	createDefaultVoxelTerrainBackground,
	createDefaultVoxelTerrainLighting,
	type EditableVoxelTerrain,
	type VoxelTerrain,
} from "../domains/VoxelTerrain/VoxelTerrain";
import { TerrainStorageService } from "../services/TerrainStorageService";
import { base64ToBytes } from "../utils/base64";

export interface DefaultVoxelStampTemplate {
	TemplateId: string;
	Name: string;
	Width: number;
	Length: number;
	Height: number;
	Resolution: number;
	Voxels: string;
	Tags: readonly string[];
}

const DEFAULT_VOXEL_STAMP_BUILTIN_ID_PREFIX = "builtin-id:";

export const DEFAULT_VOXEL_STAMP_TEMPLATES = [
	{
		TemplateId: "nature-bush",
		Name: "Bush",
		Width: 2,
		Length: 2,
		Height: 2,
		Resolution: 3,
		Voxels: "UVNWTwMAAAAmAAAAEAAAACYAAAAT/4DUoPCKz6P/UAQBCgwDfn57e3R0dHQ+dHR7fnRAez5+QHR+fn50e350dEB0dHR0fn5+dHQ=",
		Tags: [
			"path:stamps/nature",
			"builtin:starter-stamps",
			"builtin-id:nature-bush",
		],
	},
	{
		TemplateId: "nature-dead-tree",
		Name: "Dead Tree",
		Width: 3,
		Length: 3,
		Height: 6,
		Resolution: 3,
		Voxels: [
			"UVNWTwQAAQBTAAAALwAAADoAAABF+lEQUVBQUFALIBoKF18DXxEKCgoFX1+6UFBYEyAEUEpqCkJFX18IMQUCQAgIAgIOCBEBDgIR",
			"AQ4IEQMOAREBDgMRAg4EEQEOAREBDgMRAQ4FEQEOAxEFDgYRAg4CEQETBxEBEwERBhM=",
		].join(""),
		Tags: [
			"path:stamps/nature",
			"builtin:starter-stamps",
			"builtin-id:nature-dead-tree",
		],
	},
	{
		TemplateId: "nature-hedge-segment",
		Name: "Hedge Segment",
		Width: 3,
		Length: 1,
		Height: 2,
		Resolution: 3,
		Voxels: [
			"UVNWTwQAAAA6AAAAGAAAADoAAAAREf+uQLoBrkSqEd/uQJsR6rsRAQ0OCgF7e3t7e3R0dHR0dH57dHt7e3R7fnR0dHR+e357e3R7",
			"dHR0dHR0dHR7e3t0e3R0e3R0dH50e357PnR0",
		].join(""),
		Tags: [
			"path:stamps/nature",
			"builtin:starter-stamps",
			"builtin-id:nature-hedge-segment",
		],
	},
	{
		TemplateId: "nature-oak-large",
		Name: "Large Oak",
		Width: 5,
		Length: 5,
		Height: 8,
		Resolution: 3,
		Voxels: [
			"UVNWTwUAAABhAwAADQEAAGEDAAAF/6IgEfpxULr/qv/wqv+q/xEQEjEBMDDugIiIgMr+qFSyQLh/v/yA0KL/vv/ugIj2goj+/9f/",
			"/v//v/e3VUDA/fD3EP9U/lFABF//RH8VRf0rEwIzAi8LfwpfEw8KDwoPAgEREBABAc4PAgeOTY7OCP3K/9/r//oECNcuCMhMzQIE",
			"RN1F3ECE/10Mvk0z9/riIOD/vvJ31bIQ/u8TIDD/7/+r74/7rv/74/OQ///++wMgIvuAsDCi/6L7UTFwPxRVuxB30VVAEPdV/746",
			"AgGA//p/+z8hr/27fCAQ/4r/KvsQBwICr4j/Av8KC1//Z/8VDw0CAgExFf+3YTQQ//dzE1XNdQQBP//fIxEIBD4+Pj4+Pj4+Pj4+",
			"Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+PkBAQEBAZUBlQEBAQEBAQEBAZUA+QEBAZT4+Pj4+Pj57ez4+c317c3tzc3t9fXN9QD59e3tA",
			"e3tze3t7fXNzc0BzfUA+QEBAQEFAQD5APkBAQUA+QEBAQEBBQEBAQEFBQEB7QEBAQEBAQEB7e3tAQHN9c3NzPntAQEBAe0BAQEBA",
			"e0BzfX1Ac3t9fUB9fX19fX1AQEB7QHt7e0FAQXt7QXt9fXNzfXt9c31zQX1Be3t7e319c3NzfXN9fXN7e3N9e3t9fXN7fXNAfUBz",
			"QUBzfXNAe3tAe0B7e319fUBAQH1AfX19fX17e3t7fX19fX19Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+QT5BPj4+Pj4+QEBBQEFAQEBBQEFA",
			"Pj4+QEBAPj4+QEBBQEFBPj57e0A+PnNzfX19fUB9e0BAQEB7QEBAQUFBQUFBc319fUB9fX19fX1Be3NAQUBAQEBAQEF9QXt7e3t7",
			"QHt7e3t7QXtBfX1BQXt9QXtBQUFBQXtBQXt7fXt9e319e3t9e319fXN9c3Nze31AfX1zc0B9c3N9PnM+c3NzfXNzc31ze3NzQEBA",
			"QHN7e3N9fXtzQEBzQEBzc3Nzc3Nze0BAPntzQEBAQHNAe3N9c0B7fXN9fXNze3Nze3t9fX17e31zc317fXNzfXN9fXN7e31zc319",
			"fXNzc3N9fXNzc3t7fXNzfXtzc31zc3N9QXNBc3NzfXNze3N7e3tBe3tzc3NzfX1zc3N9fXt9fXN9fXt9fXNzc3tzc3Nzc3NAc3NA",
			"c3NzQEFBc3Nzc3Nzc3N9c3N9fXNzc3t7fXNzc319fX19c3N7c3Nzc3N9fXN9fXN9c0B7fXNzfXNzc3Nze3N9c3N7fXtze3tzc3Nz",
			"e0Fze0BzfUBAQH19fXNzc3Nzc3Nzc3N9fX19QX1BfX17fXNzc3tzc3tBc3NzfX19c3NzfXN9fUB9e31Ac31Ac3tAQHNAfUBAQEBA",
			"fUFAfXtAe3N9c319QXNzc0B9c0F9c319fXt9QHNzc3NzQX1zc319c3Nzc3tzc3NBQXNzQUFzQX1zc0FzQXNzc3Nzc3NBc319fX19",
			"e3Nzc0F9c31BQUF9fXNBfX1Bc0FBQXNBc3NBc0E=",
		].join(""),
		Tags: [
			"path:stamps/nature",
			"builtin:starter-stamps",
			"builtin-id:nature-oak-large",
		],
	},
	{
		TemplateId: "nature-oak-medium",
		Name: "Medium Oak",
		Width: 3,
		Length: 3,
		Height: 6,
		Resolution: 3,
		Voxels: [
			"UVNWTwUAAABtAQAAcgAAAG0BAAAFTf8goFEQ8VCAgFBQ1AMguhf/Aw8RCIgFT9//+uD4gP+o///wQP0Q/9Xv//Lgqv8g//fxUDD/",
			"/XcB/4r/7v8I7wj////d//9fRf9f/7//Iv8LvwIj///3fxP/HzcBEAQECwgIBA0BAgEzICAQEAICAQE+Pj4+Pj4+PkBAe0BAe0BA",
			"ez4+Pj4+Pj4+QD4+Pj4+Pj5AQEBlPj57e0BlQWVBQUB7e0F7e3t9c3N9fXN9c3t7c3N7e3N9fX19fX19c3t7c3N7e31zc319fX17",
			"c3Nze3tze3t7e317fXt9fX1zc3N9c3NzfXNzfXN7c3Nzc31zfXN7fXt9c3t7fXNzc3N7c3Nze3N9fXNzfXN9c3Nzc3N7e319fXNz",
			"c31zc3tze31zc3N7fX17e3N7e3t7fXtzc3t9e3t7e317e319fXt7fX17fX19e3t9fX19fX17e319e3t7fXt9c3t9fXt9e317e317",
			"fX1ze3t9fX17e3t7e317fX17e3t7e3t9fXt9fX17fX19c3N9fXN9e319fXtze3NzfXtzc319c3N9fXN7e3NzfXtzc3N9c3tzfXt9",
			"c3tzfX1zfX1zc317c3N9fXNzc3N9fXNze31zc3t9c3N9e3Nzc3NzfX19fX19c3Nzcw==",
		].join(""),
		Tags: [
			"path:stamps/nature",
			"builtin:starter-stamps",
			"builtin-id:nature-oak-medium",
		],
	},
	{
		TemplateId: "nature-oak-small",
		Name: "Small Oak",
		Width: 3,
		Length: 3,
		Height: 4,
		Resolution: 3,
		Voxels: [
			"UVNWTwQAAACYAAAANQAAAJgAAAAF36Ig+vpQcFDooPqi/1TwUN8LAisKDgqI70TdBDPzoPD+/7LzdVAQ9xAzL67/AicBFf8RBT5A",
			"QEBAQD5AQEBBQEFAPkBAZXt7Pj5AQUBAe3t7e3t7e3t7fXt7e319ZUB7e3tze3t7Pj5AQD5AQEBBfX17e317e317e3t7e3t7e3Nz",
			"c3Nzc3tzc3t7c31zfXN7fX17c3Nze3Nzc3Nzc3N9c3Nzc3N9c3Nzc3Nzc3N7fXt9c3t7fXN9fXNzc3tzQHN9fXtzc317c3Nzc31z",
		].join(""),
		Tags: [
			"path:stamps/nature",
			"builtin:starter-stamps",
			"builtin-id:nature-oak-small",
		],
	},
	{
		TemplateId: "nature-pine-tall",
		Name: "Tall Pine",
		Width: 3,
		Length: 3,
		Height: 7,
		Resolution: 3,
		Voxels: [
			"UVNWTwUAAAAsAQAAcQAAACwBAAAFF/5REFFQ6oAwwCL31UAz3Pd3CyAaChdfA18R7wjKI78IAj//30j/v4wEdxdABAH/siAi//vz",
			"MBD3c/MxoLIycPMQcrsiv7sCMwP//1d/Nx8XIwEKOzsf/wF/EQMMCAIEAwGzICBQcBAKCgIFfxcBAT4+QEBAQH6GhoaGhoaGfoaG",
			"foZ+fnx8fHyGfkB8hnx8fH58hnx8fH5+hnw+QEA+QEBAQEBAQEA+Pj5APkBAQD4+hkB8hnyGhoaGfIZ+hoZ8fIaGhoZ8hnw+QH58",
			"QHyGfHx8fHx+hnx8fHyGfH58fH58fHx8fIaGfHx+fHx+fHx8hoaGfIZ+hnyGfIZ8foaGhn5+fnx8fH5+foZ+fn58fH58fHx8fH5+",
			"fH6Ghnx+foaGfHx+hj5+fn58fn6GhoZ+hoaGfHyGfHyGfHyGhnyGfIZ8hoZ8fHx8fIZ8hn58fIZ8hnx8fHyGfH58fHx8fHx8fHx+",
			"fHx8fHyGfH6GhoaGfoZ8fn6GQHx8QH6GfoZ+fnx8fn58fHx8fHx+fnxAfH5AfHx8fkB8fECGfnx8fg==",
		].join(""),
		Tags: [
			"path:stamps/nature",
			"builtin:starter-stamps",
			"builtin-id:nature-pine-tall",
		],
	},
	{
		TemplateId: "nature-stump",
		Name: "Stump",
		Width: 2,
		Length: 2,
		Height: 2,
		Resolution: 3,
		Voxels: "UVNWTwMAAQAoAAAADgAAACYAAAAT/6DxoPC6/6r/EAECAQJAAT4FQAE+AkABTwE+AkABPgtAAU8BQAE+AQ4BQAJPAkABTwM+",
		Tags: [
			"path:stamps/nature",
			"builtin:starter-stamps",
			"builtin-id:nature-stump",
		],
	},
	{
		TemplateId: "nature-thicket-cluster",
		Name: "Thicket Cluster",
		Width: 3,
		Length: 3,
		Height: 2,
		Resolution: 3,
		Voxels: [
			"UVNWTwQAAACkAAAAOgAAAKQAAAAT/+kgoMmi//+A4LDwzM3//zACIjBxBf7MoP+ITK///4jM//8IbE93MzC6IjMzfzECAxABAQMI",
			"BQQIDn50DnsOe3R0dHR+dH50ew5+ew57e35+dH5+dHR7e3sOew57e3t7fn57e3t7fnt+dHR7fnR0DnR0dHR0dHR0ew57e350e3t+",
			"Dn4ODg57e3t7e3R+dHR+e3t+dA57fg50ew4ODnt7Dg5+dA57fn57fn50fnt+dHsOew57Dnt+dA50fnR+dHQODnt0e3R0e3R0dHR0",
			"dHR0dHR7dHR0dHR0dA5+dA4=",
		].join(""),
		Tags: [
			"path:stamps/nature",
			"builtin:starter-stamps",
			"builtin-id:nature-thicket-cluster",
		],
	},
	{
		TemplateId: "settlements-cottage",
		Name: "Cottage",
		Width: 6,
		Length: 5,
		Height: 5,
		Resolution: 3,
		Voxels: [
			"UVNWTwQAAACPBAAAKgEAAI8EAAD//6D/X/D//w8P7IrOX4jf/4DAzs4PD8/Pqv9V/1Uz//////+IVYjdiFWI3czMzMzM/fD//w+v",
			"/UDOzg+vz+9UREREu///qv//qhBz7qrM7qrM7kVERETzMyAwqv8zMDD///+q/yIzqv+q/////zMz/////zAgMDAwMPMzMDD//xEQ",
			"Vf///zMz/////1VVEVVVMDAwEBD/qv9V/1Uz/////+5ViN1ViN3MzMzMzAr/9Q////DwzvWI/ajs7/Dw/PwM7Ozfu///qv//qgU3",
			"BO6qzO6qzO5URERED///8Prf8Pr8/gzs7EVEREQ//6r/qv+q/yIz//////////8zAwIDEwMD/zOq/wIDM///AwM//////////zMz",
			"VVVVVREDAwMBATP//wMDEVUBBAQOFAQEFA4OFg4WFhYEBBQUBAQODgQEFBQEBA4OFhAWEBAQnp5MTFFMTExRUQ4WDhYWFkxMDg5O",
			"Tg5OTg4ODkxMTFFOTExMTlEWEBYOoqIOEA4OTkxOTBAOTk5MTgQEFA4EBBQOEBAQngQEFA4EBBQOEJ4QEAQEDg4EBA4OBAQODgQE",
			"Dg4EBA4OBAQODgQEDg4EBA4ODg4QFqIWTEwOTkwOTk4ODqIWEBZMTA5RUQ5OUU5RTk5MTk5OUVFRTk5OUU4EBBQUBAQODgQEFA4E",
			"BA4UEBYQFhYOFg4Qng5MTExOTExMTFFOEBYOFhYOFg6iFg4OTE5OTA4OTk4OTk5MTA4OTEwEBA4OBAQODgQEDhQEBA4UEJ4QEAQE",
			"Dg4EBA4OBAQODgQEDj8ODj8/BAQEBASiFhAQTk5RTg5OThBOTA4OPw5RTk5ODk5ODk5ODg5MTExMTExMTExMTE5RTExRTk5RTExM",
			"TE5OTExRTE5RUU5MTE5OUVFMTExMTk5RTlFRUUxMTExMTk5MTExMUU5OTlFOTk5MTExMTk5MTE5RUU5OTExOTE5OTlFOTk5OTlFM",
			"TExOUUxMTE5RTk5OTk5OUU5RTkxOTlFOTkxMTFFMTk5MTkxMTlFOTkxMTExMTExMTExMTk5MTE5OTkxOUUxMUU5OUUxMTExMUUxM",
			"Tk5OUVFMTk5RTlFMTkxMTk5MTFFOTlFMTk5OUU5OTk5RTE5MUU5OTExMTFFRUU5MTFFOTlFMTExMTExMTExMTExMTExMTExMBAQU",
			"DgQEFA4WFhYWBAQUDgQEFA4WFhYWBAQODgQEDg4EBA4OBAQODgQEDg4EBA4OBAQODgQEDg4WFhYWTEwOUUwOUU4WFhYWTEwOUVEO",
			"Tk5OTE5OTlFRTkxRTlFOTk5OBAQUDgQEDhQWFg4WDhYEBA4OBAQUFAQEDg4EBBQUFhYWFhAQEJ4WFg4WDhZMTA5OTg4OTlFRTExM",
			"UUxMTBYWFhYQohAOUU4ODkxMTk4OEE5ODg5RTkxMTE5RTExMBAQODgQEDg4EBA4/BAQODj8/Dg4EBA4OBAQODgQEDhQEBA4UEBAQ",
			"ngQEBAQEUT8ODg5OTkxMDk5RDk5MEBCiFlFOUVEQTk4OUVFMTA4OTEwEBA4OBAQUFAQEDhQEBBQOEBCeEBCeFg4WDqIQDg6iFhYO",
			"Dg5OTg4OTlEOTlEODk5RDg5OUUxMTFFOTExMDg5MTExMTExMTFFOTk5OTk5OTExMTExRUVFOTExMTExMTExMTlFRTk5OTExOTkxM",
			"Tk5OTFFRTk5OTk5OTk5OTFFOTk5OUUxMTExOTlFMTExBQUE/QUFBQU5OTk5OTlFRQUFBQT9BQUFMTExMTExMTExMTD9BPz9BQT8/",
			"TExMTFFOTExOUUxMTExMTE5OTlFRTExOTFFMTk5MTExMTExOUUxOTlFOTk5OUU5OUUxMTE5RUVFMTExMTE5OTk5MTFFRTkxOTk5O",
			"Tk5RTk5RTk5OTkxMUU5MTExMTExMTExMTExMTExMTExMTExOTFFOTk5MTE5MUU5MTkxMTExMTExMTExM",
		].join(""),
		Tags: [
			"path:stamps/settlements",
			"builtin:starter-stamps",
			"builtin-id:settlements-cottage",
		],
	},
	{
		TemplateId: "stone-boulder-large",
		Name: "Large Boulder",
		Width: 3,
		Length: 3,
		Height: 2,
		Resolution: 3,
		Voxels: [
			"UVNWTwQAAQCeAAAALQAAAJYAAAAR//ug+LD7/6r/VfAQ//cgshAQ////u/+v/wL/Vf///1cjIDsBAREDAwIDAQUBBAEHAwQBCQEH",
			"AgkDBAEHAwQBBwIEAQcBCQIEAQcGCQEHAQkBBAEJAQcBBAEHBAQBBwMEAQcDBAEJAgQBBwEEAQcBCQIEBAkCBAIHAgQCBwMEAQcC",
			"BAIHAQQCBwEECgcDBAEHBAQCBwIEBAcBBAQHBAQCBwIEAQcCBAIHAwQBBwMEAgcCBAEHAgQDBwIEBAkBBAMJBQQ=",
		].join(""),
		Tags: [
			"path:stamps/stone",
			"builtin:starter-stamps",
			"builtin-id:stone-boulder-large",
		],
	},
	{
		TemplateId: "stone-boulder-small",
		Name: "Small Boulder",
		Width: 2,
		Length: 2,
		Height: 1,
		Resolution: 3,
		Voxels: "UVNWTwMAAAAfAAAACwAAAB8AAAAR86Bwu/8gAgMrPwQHBAQEBAQJBAQHBAQJBwQEBAcJCQQEBwQEBAcHBAQ=",
		Tags: [
			"path:stamps/stone",
			"builtin:starter-stamps",
			"builtin-id:stone-boulder-small",
		],
	},
	{
		TemplateId: "stone-rock-cluster",
		Name: "Rock Cluster",
		Width: 4,
		Length: 3,
		Height: 2,
		Resolution: 3,
		Voxels: [
			"UVNWTwQAAABzAAAAJQAAAHMAAAARs7AwsCD38FAg/1U7Ff8r/wK7un+AG3f/Fff/AR8BMAEHP1cCBAQEBAQEBAQEBAQJCQQEBAcE",
			"BAkEBAcEBwkECQcECQkEBAQJBAQEBwQEBAcHCQQECQcECQQEBAQEBAQHBwQEBAkEBAkEBAQJCQQEBwQEBAQJCQkHBwkJBAQEBwQE",
			"BwcEBwcJBAcECQQEBAcEBAQEBwQHBA==",
		].join(""),
		Tags: [
			"path:stamps/stone",
			"builtin:starter-stamps",
			"builtin-id:stone-rock-cluster",
		],
	},
] as const satisfies readonly DefaultVoxelStampTemplate[];

// The template's Voxels are a base64 string (readable, diffable source); the
// canonical payload form is bytes, so decode once here when building the stamp.
function createDefaultVoxelStamp(
	stamp: DefaultVoxelStampTemplate
): EditableVoxelTerrain {
	return {
		Id: crypto.randomUUID(),
		Name: stamp.Name,
		Width: stamp.Width,
		Length: stamp.Length,
		Height: stamp.Height,
		Resolution: stamp.Resolution,
		Voxels: base64ToBytes(stamp.Voxels),
		Lighting: createDefaultVoxelTerrainLighting(),
		Background: createDefaultVoxelTerrainBackground(),
		Tags: [...stamp.Tags],
	};
}

export function getDefaultVoxelStampTemplateId(
	terrain: Pick<VoxelTerrain, "Tags">
): string | null {
	const tag = terrain.Tags?.find((candidate) =>
		candidate.startsWith(DEFAULT_VOXEL_STAMP_BUILTIN_ID_PREFIX)
	);
	return tag?.slice(DEFAULT_VOXEL_STAMP_BUILTIN_ID_PREFIX.length) ?? null;
}

export function createDefaultVoxelStamps(
	existingTemplateIds: ReadonlySet<string> = new Set()
): EditableVoxelTerrain[] {
	return DEFAULT_VOXEL_STAMP_TEMPLATES
		.filter((stamp) => !existingTemplateIds.has(stamp.TemplateId))
		.map(createDefaultVoxelStamp);
}

/**
 * Splits an EditableVoxelTerrain into a canonical (payload-free) terrain whose
 * voxels have been materialized into the per-client store and whose metadata
 * (ContentHash / VoxelCount / PreviewColor) has been stamped. The campaign owns
 * only the returned metadata object; the payload is persisted to IndexedDB the
 * next time the campaign is saved (prepareCampaignForStorage).
 */
export function commitEditableVoxelTerrain(
	editable: EditableVoxelTerrain
): VoxelTerrain {
	const { Voxels, ...meta } = editable;
	TerrainStorageService.materialize(meta, Voxels);
	return meta;
}

export function addMissingDefaultVoxelStamps(campaign: {
	VoxelTerrains?: VoxelTerrain[];
}): number {
	campaign.VoxelTerrains ??= [];
	const existingTemplateIds = new Set<string>();
	for (const terrain of campaign.VoxelTerrains) {
		const templateId = getDefaultVoxelStampTemplateId(terrain);
		if (templateId) existingTemplateIds.add(templateId);
	}

	const missing = createDefaultVoxelStamps(existingTemplateIds);
	for (const editable of missing) {
		campaign.VoxelTerrains.push(commitEditableVoxelTerrain(editable));
	}
	return missing.length;
}
